/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nolasco_johnharold_k.o;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author CSHS-PC105
 */
public class field extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(field.class.getName());
       int type = 0;
       int attack1;
        int attack2;
         int attack3;
          int attack4;
           int accuracy1;
           int accuracy2;
           int accuracy3;
           int accuracy4;
           int choice;
           Gordex arley;
        Gordex nolan;
        Random rand = new Random();
                             
       
       
       
       
    /**
     * Creates new form field
     */
    public field() {
        initComponents();
         setLocationRelativeTo(null);
         
    }
    
         
          public void fight(){
         Scanner sc = new Scanner(System.in);
 
        Gordex arley =  new Gordex("arley",100,20,10,30);
 
        arley.addMove(0,new Move("Global Shock",50,95));
        arley.addMove(1,new Move("Quick Sleep",55,100));
        arley.addMove(2,new Move("Iron phone",45,85));
        arley.addMove(3,new Move("DELETE",100,100));
 
        Gordex nolan =
                new Gordex("nolan",1000,18,12,20);
 
        nolan.addMove(0,new Move("VOID",80,100));
        nolan.addMove(1,new Move("UNIVERS",50,95));
        nolan.addMove(2,new Move("BLACK HOLE",50,100));
        nolan.addMove(3,new Move("NOVA Beam",35,85));
       
 
        while(arley.isAlive() && nolan.isAlive()){
 
            arley.displayStatus();
            nolan.displayStatus();
 
            System.out.println("\nChoose Move:");
 
            for(int i=0;i<4;i++){
                System.out.println((i+1)+"." + arley.moves[i].name);
                  }
 
            int choice = sc.nextInt()-1;
 
            if(arley.speed >= nolan.speed){
 
                arley.attack(nolan,choice);
 
                if(nolan.isAlive()){
 
                    int enemyMove =
                            (int)(Math.random()*4);
 
                    nolan.attack(arley,enemyMove);
 
                }
 
            }else{
 
                int enemyMove =
                        (int)(Math.random()*4);
 
                nolan.attack(arley,enemyMove);
 
                if(arley.isAlive()){
 
                    arley.attack(nolan,choice);
 
                }
 
            }
 
            System.out.println("-------------------");
            
            
 
        }
 
        if(arley.isAlive())
            System.out.println("You Win!");
        else
            System.out.println("You Lose!");
      }
          
          public int getSelectedMove() {

    if (jRadioButton1.isSelected()) {
        return 0;
    }

    if (jRadioButton2.isSelected()) {
        return 1;
    }

    if (jRadioButton3.isSelected()) {
        return 2;
    }

    if (jRadioButton4.isSelected()) {
        return 3;
    }

    return -1; // No move selected
}
       
public void playTurn() {

    int choice = getSelectedMove();

    if(choice == -1){
        JOptionPane.showMessageDialog(this, "Please select a move.");
        return;
    }

    // Player attacks first
    arley.attack(nolan, choice);

    // Enemy attacks if still alive
    if(nolan.isAlive()){
        int enemyMove = rand.nextInt(4);
        nolan.attack(arley, enemyMove);
    }

    // Update HP bars
    jProgressBar1.setValue(arley.hp);
    jProgressBar2.setValue(nolan.hp);

    // Check winner
    if(!nolan.isAlive()){
        JOptionPane.showMessageDialog(this, "You Win!");
    }
    else if(!arley.isAlive()){
        JOptionPane.showMessageDialog(this, "You Lose!");
    }
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar2.setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 180, 20));

        jProgressBar1.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, 180, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nolasco_johnharold_k/o/sidee.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nolasco_johnharold_k/o/sss1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 200, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nolasco_johnharold_k/o/place1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 0));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Global Shock");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Iron phone");
        jRadioButton3.addActionListener(this::jRadioButton3ActionPerformed);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("DELETE");
        jRadioButton4.addActionListener(this::jRadioButton4ActionPerformed);

        jButton1.setText("ATTACK");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addGap(203, 203, 203)
                .addComponent(jButton1)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       int choice = -1;

    if (jRadioButton1.isSelected()) {
        choice = 0;
    } else if (jRadioButton2.isSelected()) {
        choice = 1;
    } else if (jRadioButton3.isSelected()) {
        choice = 2;
    } else if (jRadioButton4.isSelected()) {
        choice = 3;
    }

    if (choice == -1) {
        JOptionPane.showMessageDialog(this, "Select a move first.");
        return;
    }

      arley.attack(nolan, choice);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      playTurn();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new field().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
