/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmbank;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author CSHS-PC105
 */
public class AtmForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AtmForm.class.getName());
    private BankAccount account = new BankAccount();
private Bank bank = new Bank(account);

private String currentPin = "1234";
private String accountName;
   
    
    /**
     * Creates new form AtmForm
     */
   public AtmForm(String name, String pin) throws Exception {

    initComponents();

    accountName = name;
    currentPin = pin;

    double savedBalance = CSVManager.getBalance(name);

    account.setBalance(savedBalance);

    setLocationRelativeTo(null);

    updateBalance();

    startClock();

    jTextArea1.setEditable(false);

    jTextArea1.append(
        "===== Transaction History =====\n"
    );

}

    private void updateBalance() {

    try {

        jLabel1.setText("Balance : ₱" + bank.checkBalance());

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
    
    private void startClock() {

    Timer timer = new Timer(1000, e -> {

        SimpleDateFormat sdf =
                new SimpleDateFormat("MMMM dd, yyyy HH:mm:ss");

        jLabel2.setText(sdf.format(new Date()));

    });

    timer.start();

}

    
    
    

    
    private void addHistory(String message) {

    jTextArea1.append(message + "\n");

}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("Balance :  0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Date & Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Amount:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, 83, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 96, 149, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 24, -1, 336));

        jButton1.setText("Deposit");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 107, -1));

        jButton2.setText("Withdraw");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 107, -1));

        jButton3.setText("Check Balance");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 244, -1, -1));

        jButton4.setText("Change PIN");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 107, -1));

        jButton5.setText("Reset Account");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, 107, -1));

        jButton6.setText("Exit");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 405, 107, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbank/2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
     try {

        double amount = Double.parseDouble(jTextField2.getText());


        // THROW kapag invalid ang amount
        if(amount <= 0){

            throw new Exception("Withdraw amount must be greater than zero.");

        }


        // CHECK BALANCE
        double balance = bank.checkBalance();


        // THROW kapag kulang ang pera
        if(amount > balance){

            throw new Exception("Insufficient balance.");

        }


        // Withdraw
        bank.withdraw(amount);


        // Save bagong balance sa CSV
        double newBalance = bank.checkBalance();

        CSVManager.updateBalance(
                accountName,
                newBalance
        );


        updateBalance();


        addHistory("Withdraw : ₱" + amount);


        JOptionPane.showMessageDialog(
                this,
                "Withdraw Successful!"
        );


        jTextField2.setText("");


    }

    catch(NumberFormatException e){

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid number."
        );

    }

    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         String newPin = JOptionPane.showInputDialog(
            this,
            "Enter New PIN"
    );


    if(newPin != null && !newPin.isEmpty()){


        currentPin = newPin;


        CSVManager.updatePin(
                accountName,
                newPin
        );


        addHistory("PIN Changed");


        JOptionPane.showMessageDialog(
                this,
                "PIN Changed Successfully"
        );

    }

    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      dispose();

    new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
     try {

        double amount = Double.parseDouble(jTextField2.getText());


        // THROW ERROR kapag invalid ang amount
        if(amount <= 0){

            throw new Exception("Deposit amount must be greater than zero.");

        }


        // Deposit
        bank.deposit(amount);


        // Save sa CSV
        double newBalance = bank.checkBalance();

        CSVManager.updateBalance(
                accountName,
                newBalance
        );


        updateBalance();

        addHistory("Deposit : ₱" + amount);


        JOptionPane.showMessageDialog(
                this,
                "Deposit Successful!"
        );


        jTextField2.setText("");


    }
    catch(NumberFormatException e){

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid number."
        );

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
       try {

        double balance = bank.checkBalance();

        JOptionPane.showMessageDialog(
                this,
                "Your current balance is: ₱" + balance,
                "Check Balance",
                JOptionPane.INFORMATION_MESSAGE
        );

        addHistory("Checked Balance : ₱" + balance);

        updateBalance();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        int answer = JOptionPane.showConfirmDialog(
            this,
            "Reset Name and PIN?",
            "Confirm Reset",
            JOptionPane.YES_NO_OPTION
    );

    if(answer == JOptionPane.YES_OPTION){

        try {

            String newName = JOptionPane.showInputDialog(
                    this,
                    "Enter New Name:"
            );

            String newPin = JOptionPane.showInputDialog(
                    this,
                    "Enter New PIN:"
            );


            if(newName != null && newPin != null
                    && !newName.isEmpty()
                    && !newPin.isEmpty()) {


                double currentBalance = bank.checkBalance();


                CSVManager.resetAccount(
                        accountName,
                        newName,
                        newPin
                        
                );


                accountName = newName;
                currentPin = newPin;


                addHistory("Account Name and PIN Reset");


                JOptionPane.showMessageDialog(
                        this,
                        "Account Reset Successful!"
                );


            }


        } catch(Exception e){

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );

        }

    }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        try {

            new AtmForm("admin", "1234").setVisible(true);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );

        }
    });

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
